---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-tests
data:
  NOSETESTS_ATTR: "!fails_on_rgw"
  NOSETESTS_OPTIONS: "-v"
  s3test.conf: |
    [DEFAULT]
    host = ceph-rgw.ceph.svc.cluster.local
    port = 8088
    is_secure = no
    
    [fixtures]
    bucket prefix = s3-tests-{random}-
    
    [s3 main]
    user_id = s3-tests
    display_name = s3-tests
    email = s3-tests@example.com
    access_key = AAAAAAAAAAAAAAAAAAAA
    secret_key = 0000000000000000000000000000000000000000
    kms_keyid =
    [s3 alt]
    user_id = s3-tests-2
    display_name = s3-tests-2
    email = s3-tests-2@example.com
    access_key = BBBBBBBBBBBBBBBBBBBB
    secret_key = 0000000000000000000000000000000000000000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: s3-tests
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name:  s3-tests
          image: ceph-s3-tests
          imagePullPolicy: Always
          env:
            - name: NOSETESTS_ATTR
              valueFrom:
                configMapKeyRef:
                  name: s3-tests
                  key: NOSETESTS_ATTR
            - name: NOSETESTS_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: s3-tests
                  key: NOSETESTS_OPTIONS
          volumeMounts:
            - name: s3-tests
              mountPath: /s3test.conf
              subPath: s3test.conf
              readOnly: true
      volumes:
        - name: s3-tests
          configMap:
            name: s3-tests
            defaultMode: 0444
